version: "3.9"
services:
  es01:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.17.0"
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
  app_server:
    build: ./server
    ports:
      - "8080:8080"
    depends_on:
      - "es01"
  app_client:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - "app_server"
